# Generated by Django 5.1.1 on 2024-10-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('sku', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
    ]
