# Generated by Django 5.1.1 on 2024-10-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(default='No details', max_length=200),
            preserve_default=False,
        ),
    ]
