# Generated by Django 5.1.1 on 2024-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bible_hint',
            field=models.CharField(default='', max_length=50),
        ),
    ]
